movie/movie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]

movie/movieapp/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

from. import views
app_name='movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>', views.delete, name='delete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img  = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movie/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm
# Create your views here.



def index(request):
    movie = Movie.objects.all()
    context = {'movie_list': movie
               }
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')

    return render(request, 'add.html')


def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,
                                       'movie':movie
                                       })

def delete(request,id):
    if request.method=="POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movie/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
 {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name">
    <input type="text" name="desc" placeholder="Enter movie detail">
    <input type="text" name="year" placeholder="Enter movie year">
    <input type="file" name="img">
    <input type="submit">
</form>
{% endblock %}

movie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body style="background-color:rgb(18, 133, 94)";>
<nav class="navbar navbar-light bg-dark">
  <span class="navbar-brand mb-0 h1">Online Movie Store</span>
    <br>
     <div class="container-fluid" >
            <div>
                <a  class="btn btn-info"  href="{% url 'movieapp:add_movie'%}">Add movie</a>
            </div>
        </div>

</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token%}
  Are you sure want to delete?<br>
  <input type="submit">

</form>
{% endblock %}

movie/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>


      <div class="col-md-6">
        <h3>{{movie.name}}</h3>
        <h5>{{movie.desc}}</h5>
        <h5>{{movie.year}}</h5>
        <h5><a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a></h5>

      </div>
    </div>
</div>

{% endblock %}

movie/templates/edit.html
<form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p}}
      <input type="submit">
</form>

movie/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
         <div class="row">
             {% for i in movie_list%}
             <div class="col-md-4">
                 <br>
                 <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{ i.img.url}}" alt="Card image cap" width="200px" height="300px";>
  <div class="card-body">
    <h5 class="{{i.name}}">Card title</h5>
    <p class="card-text">"{{i.desc}}"</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">detail</a>
  </div>
</div>

             </div>
             {% endfor %}
         </div>
    <br>

</div>
{% endblock %}